invoicing_system/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('invoicing/', include("invoicing.urls")),
    path('reports/', include("reports.urls")),
    path('company/', include("company.urls")),
    path('users/', include("users.urls")),
    path('users/', include("django.contrib.auth.urls")),
    path('admin/', admin.site.urls),
]

reports/urls.py
from django.urls import path
from . import views

app_name = 'reports'
urlpatterns = [
    path('', views.index, name='index'),
    path('new_report/<int:customer_id>', views.new_report, name='new_report'),
    path('edit_report/<int:report_id>', views.edit_report, name='edit_report'),
    path('delete_report/<int:report_id>', views.delete_report, name='delete_report'),
    ]

users/urls.py
from django.urls import path
from . import views

app_name = 'users'
urlpatterns = [
    path('login_user', views.login_user, name='login_user'),
    ]

reports/models.py
from django.db import models
from django.utils import timezone


class Report(models.Model):
    objects = models.Manager()

    customer = models.ForeignKey("invoicing.Customer",
                                 on_delete=models.CASCADE,
                                 verbose_name="customer",
                                 related_name="reports",
                                 default=1)
    name = models.CharField(max_length=100, blank=True)
    address = models.CharField(max_length=200, blank=True)
    phone = models.CharField(max_length=40, blank=True)
    email = models.CharField(max_length=100, blank=True)
    date_time = models.CharField(max_length=20, blank=True)
    number = models.CharField(max_length=20, blank=True)
    boiler = models.CharField(max_length=200, blank=True)
    comission = models.CharField(max_length=20, blank=True)
    gas_type = models.CharField(max_length=50, blank=True)
    thermostat = models.CharField(max_length=200, blank=True)
    maintenance = models.BooleanField(default=False)
    repairs = models.BooleanField(default=False)
    repairs_info = models.CharField(max_length=500, blank=True)
    inspection = models.BooleanField(default=False)
    flue_gas_type = models.CharField(max_length=20, blank=True)
    flue_gas_check = models.BooleanField(default=False)
    air_check = models.BooleanField(default=False)
    safety_systems_check = models.BooleanField(default=False)
    gas_conn_check = models.BooleanField(default=False)
    gas_water_tightness_check = models.BooleanField(default=False)
    system_hydr_check = models.BooleanField(default=False)
    anode_check = models.CharField(max_length=20, blank=True)
    heat_carrier = models.CharField(max_length=200, blank=True)
    yes_check = models.BooleanField(default=False)
    maintenance_need_check = models.BooleanField(default=False)
    repairs_need_check = models.BooleanField(default=False)
    notes = models.CharField(max_length=500, blank=True)
    date_created = models.DateTimeField(default=timezone.now())

reports/forms.py
from django.forms import ModelForm
from .models import Report

class ReportForm(ModelForm):
    class Meta:
        model = Report
        # fields = '__all__'
        exclude = ['customer']

reports/views.py
from datetime import datetime
from django.http import HttpResponse
from django.shortcuts import render, redirect
from .forms import ReportForm
from .models import Report
from invoicing.models import Customer
from django.utils import timezone


def index(request):

    return render(request, "reports/index.html")

def new_report(request, customer_id):
    # read document number
    try:
        with open('count.txt') as count_file:
            content = count_file.read()
            count = int(content)
    except Exception:
        count = 1

    customer = Customer.objects.get(pk=customer_id)
    form = ReportForm(initial={
        'name': customer.name,
        'address': customer.address,
        'phone': customer.phone,
        'email': customer.email,
        'date_time': timezone.now().strftime('%d.%m.%Y'),
        'number': f"{datetime.today().strftime('%d%m%y')}-{count}"
    })

    context = {"form": form, "customer": customer}

    if request.method == "POST":
        form = ReportForm(request.POST)
        if form.is_valid():
            form.instance.customer = customer
            form.save()
            # increment number for the next document
            with open('count.txt', 'w') as count_file:
                count_file.write(str(count + 1))
            return redirect('customer_profile', customer_id=customer.id)

    return render(request, 'reports/new_report.html', context)


def edit_report(request, report_id):
    obj = Report.objects.get(pk=report_id)
    if request.method == "GET":
        form = ReportForm(instance=obj)
    else:
        form = ReportForm(request.POST, instance=obj)
        if form.is_valid():
            form.save()
            return redirect(request.META.get('HTTP_REFERER'))
    return render(request, 'reports/edit_report.html', {"form": form})

def delete_report(request, report_id):
    Report.objects.get(pk=report_id).delete()
    return redirect(request.META.get('HTTP_REFERER'))

reports/templates/reports/all_reports.html
<div class="container">
    <table class="table">
        <tr>
            <th>ID</th>
            <th>Number</th>
            <th>Customer</th>
            <th>Address</th>
            <th>Boiler</th>
            <th></th>
            <th></th>
        </tr>
        {% for report in reports %}
        <tr>
            <td>{{ report.id }}</td>
            <td>{{ report.number  }}</td>
            <td>{{ report.customer.name }}</td>
            <td>{{ report.address }}</td>
            <td>{{ report.boiler }}</td>
            <td><a href="{% url 'reports:edit_report' report.id %}">Edit</a></td>
            <td><a href="{% url 'reports:delete_report' report.id %}">Delete</a></td>
        </tr>
        {% endfor %}
    </table>
</div>

reports/templates/reports/edit_report.html
{% extends "invoicing/layout.html" %}
{% load crispy_forms_tags %}
{% block body %}
<div class="container">
    <h1>Edit</h1>

    
    <form method="post">
        {% csrf_token %}
        {{ form|crispy }}
        <input type="submit" value="Submit">
    </form>
    


</div>

{% endblock %}

reports/templates/reports/index.html
{% extends "invoicing/layout.html" %}
{% load crispy_forms_tags %}
{% block body %}
<div class="container">
    <h1>Reports</h1>

</div>

{% endblock %}

reports/templates/reports/new_report.html
{% extends "invoicing/layout.html" %}
{% load crispy_forms_tags %}
{% block body %}
<div class="container">
    <h1>Report</h1>

    
    <form action="{% url 'reports:new_report' customer.id %}" method="post">
        {% csrf_token %}
        {{ form|crispy }}
        <input type="submit" value="Submit">
    </form>
    


</div>

{% endblock %}