company/urls.py
from django.urls import path
from . import views

app_name = 'company'
urlpatterns = [
    path('', views.company_info, name='company_info'),
    ]

invoicing/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('new_customer', views.add_new_customer, name='new_customer'),
    path('customers', views.all_customers, name='all_customers'),
    path('customer_profile/<int:customer_id>', views.customer_profile, name='customer_profile'),
    path('<int:customer_id>/new_invoice', views.new_invoice, name='new_invoice'),
    path('<int:customer_id>/invoice/<int:invoice_id>', views.process_invoice, name='process_invoice'),
    path('delete/<int:customer_id>', views.delete_customer, name='delete_customer'),
    path('delete_invoice/<int:invoice_id>', views.delete_invoice, name='delete_invoice'),
    path('generate_pdf/<int:invoice_id>', views.generate_pdf, name='generate_pdf'),
    path('all_invioces', views.all_invoices, name='all_invoices'),
    path('delete_line/<int:line_id>', views.delete_line, name='delete_line'),
    path('scrape', views.scrape, name='scrape'),
    path('scraped/<str:name>', views.scraped, name='scraped'),
    path('toggle_paid/<int:invoice_id>', views.toggle_paid, name='toggle_paid')
]

invoicing_system/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('invoicing/', include("invoicing.urls")),
    path('reports/', include("reports.urls")),
    path('company/', include("company.urls")),
    path('users/', include("users.urls")),
    path('users/', include("django.contrib.auth.urls")),
    path('admin/', admin.site.urls),
]

reports/urls.py
from django.urls import path
from . import views

app_name = 'reports'
urlpatterns = [
    path('', views.index, name='index'),
    path('new_report/<int:customer_id>', views.new_report, name='new_report'),
    path('edit_report/<int:report_id>', views.edit_report, name='edit_report'),
    path('delete_report/<int:report_id>', views.delete_report, name='delete_report'),
    ]

users/urls.py
from django.urls import path
from . import views

app_name = 'users'
urlpatterns = [
    path('login_user', views.login_user, name='login_user'),
    ]

invoicing/models.py
from django.db import models
from num2words import num2words
from datetime import datetime, timedelta


VAT = 1.21

class Customer(models.Model):
    objects = models.Manager()
    name = models.CharField(max_length=200)
    address = models.CharField(max_length=200)
    city = models.CharField(max_length=200, blank=True)
    registration = models.CharField(max_length=20, blank=True)
    vat = models.CharField(max_length=20, blank=True)
    phone = models.CharField(max_length=40, blank=True)
    email = models.CharField(max_length=100, blank=True)
    notes = models.CharField(max_length=400, blank=True)

    def __str__(self):
        return f'{self.name} {self.address}'


class Invoice(models.Model):
    objects = models.Manager()
    number = models.CharField(max_length=20)
    create_date = models.DateTimeField('date created')
    due_time = models.IntegerField(default=5)

    customer = models.ForeignKey(Customer, on_delete=models.CASCADE, related_name='invoices', default=1)
    paid = models.BooleanField(default=False)

    from .pdf_gen import generate_pdf

    def __str__(self):
        return f'{self.number}'

    def due_date(self):
        date = self.create_date + timedelta(days=self.due_time)
        return date.strftime('%d.%m.%Y.')

    def total(self):
        return sum([line.amount * line.price for line in self.lines.all()])

    def vat(self):
        return self.total() * VAT - self.total()

    def total_with_vat(self):
        return self.total() * VAT

    def num_to_words(self):
        euros = num2words(int(self.total_with_vat() // 1), lang='lv')
        cents = round((self.total_with_vat() - self.total_with_vat() // 1) * 100)
        return f"Summa vārdos: {euros} eiro, {cents} centi"

class Line(models.Model):
    objects = models.Manager()
    item = models.CharField(max_length=200)
    amount = models.FloatField(default=1)
    vat_included = models.BooleanField(default=False, )
    price = models.FloatField(default=0)
    invoice = models.ForeignKey(Invoice, on_delete=models.CASCADE, related_name='lines', default=1)

    def total(self):
        return self.amount * self.price

    def __str__(self):
        return f'{self.item} - {self.amount} - {self.price}'

class Phone(models.Model):
    num = models.CharField(max_length=200)

    def __str__(self):
        return f"Phone: {self.num}"

invoicing/forms.py
from django.forms import ModelForm
from django import forms
from .models import Customer, Phone, Invoice, Line

class CustomerForm(ModelForm):
    class Meta:
        model = Customer
        fields = '__all__'

class InvoiceForm(ModelForm):
    class Meta:
        model = Invoice
        fields = '__all__'

class LineForm(ModelForm):
    vat_included = forms.CheckboxInput()

    class Meta:
        model = Line
        fields = ['item', 'amount', 'price', 'vat_included']

class SearchCompany(forms.Form):
    search_string = forms.CharField()

class DueTime(forms.Form):
    due_time = forms.IntegerField()

invoicing/views.py
from django.http import HttpResponse
from django.shortcuts import render, redirect
from .models import Customer, Invoice, Line
from .forms import CustomerForm, LineForm, SearchCompany, DueTime
from django.http import HttpResponseRedirect
from datetime import datetime
from .scrape_company import get_company, get_company_data
from reports.models import Report

VAT = 1.21


def index(request):
    context = {
        "invoices": Invoice.objects.all().order_by('-id')[:5],
        "reports": Report.objects.all().order_by('-id')[:5]
    }

    return render(request, "invoicing/index.html", context)


def add_new_customer(request):
    form = CustomerForm()
    customers = Customer.objects.all()
    context = {
        "form": form,
        "customers": customers
    }
    if request.method == "POST":
        form = CustomerForm(request.POST)
        if form.is_valid():
            currentcustomer = form.save()
            return redirect('customer_profile', customer_id=currentcustomer.id)
            # return redirect('all_customers')
        else:
            print("not valid form")
    return render(request, "invoicing/new_customer.html", context)


def all_customers(request):
    context = {"customers": Customer.objects.all()}
    return render(request, "invoicing/customers.html", context)


def customer_profile(request, customer_id):
    customer = Customer.objects.get(pk=customer_id)

    context = {
        "customer": customer,
        "invoices": customer.invoices.all(),
        "reports": customer.reports.all(),
    }
    return render(request, "invoicing/customer_profile.html", context)


def delete_customer(request, customer_id):
    customer = Customer.objects.get(pk=customer_id)
    customer.delete()
    return redirect('all_customers')


def new_invoice(request, customer_id):
    customer = Customer.objects.get(pk=customer_id)

    invoice = Invoice(number=6, create_date=datetime.now(), customer=customer)
    invoice.save()

    try:
        with open('invoice_number.txt') as count_file:
            content = count_file.read()
            count = int(content)
    except Exception:
        count = 1

    invoice.number = f"{datetime.today().strftime('%d%m%y')}-{count}"

    # increment number for the next document
    with open('invoice_number.txt', 'w') as count_file:
        count_file.write(str(count + 1))

    invoice.save()
    return redirect('process_invoice', customer_id=customer.id, invoice_id=invoice.id)


def process_invoice(request, customer_id, invoice_id):
    invoice = Invoice.objects.get(pk=invoice_id)
    lines = Line.objects.filter(invoice=invoice)
    form = LineForm()
    due_form = DueTime(initial={'due_time': 5})

    # item names from database for autocomplete (datalist)
    previous_items = set([line.item for line in Line.objects.all()])

    customer = Customer.objects.get(pk=customer_id)
    context = {"invoice": invoice,
               "form": form,
               "lines": lines,
               "customer": customer,
               "items": previous_items,  # datalist items
               "due_form": due_form,
               }

    if request.method == "POST":
        if 'add-line' in request.POST:
            form = LineForm(request.POST)
            if form.is_valid():
                item = form.cleaned_data["item"]
                amount = form.cleaned_data["amount"]
                price = form.cleaned_data["price"]
                vat_included = form.cleaned_data["vat_included"]
                line = Line(invoice=invoice, item=item, amount=amount, price=price, vat_included=vat_included)
                if line.vat_included:
                    line.price /= VAT
                line.save()
                return HttpResponseRedirect(request.path_info)

    if request.method == "POST" and "save-invoice" in request.POST:
        due_form = DueTime(request.POST)

        if due_form.is_valid():
            invoice.due_time = due_form.cleaned_data["due_time"]
            invoice.save()
            return redirect('customer_profile', customer_id=customer.id)
        else:
            print("not valid form")

    return render(request, "invoicing/new_invoice.html", context)


def delete_invoice(request, invoice_id):
    invoice = Invoice.objects.get(pk=invoice_id)
    customer = invoice.customer
    invoice.delete()
    return redirect(request.META.get('HTTP_REFERER'))
    # return redirect('customer_profile', customer_id=customer.id)


def generate_pdf(request, invoice_id):
    invoice = Invoice.objects.get(pk=invoice_id)
    Invoice.generate_pdf(invoice)
    return redirect(request.META.get('HTTP_REFERER'))


def all_invoices(request):
    context = {"invoices": Invoice.objects.all()}
    return render(request, "invoicing/all_invoices.html", context)


def toggle_paid(request, invoice_id):
    invoice = Invoice.objects.get(pk=invoice_id)
    if invoice.paid:
        invoice.paid = False
    else:
        invoice.paid = True
    invoice.save()
    return redirect(request.META.get('HTTP_REFERER'))


def delete_line(request, line_id):
    line = Line.objects.get(pk=line_id)
    line.delete()
    return redirect(request.META.get('HTTP_REFERER'))


def scrape(request):
    form = SearchCompany()
    companies = []
    if request.method == "POST":
        form = SearchCompany(request.POST)
        if form.is_valid():
            search_string = form.cleaned_data["search_string"]
            companies = get_company_data(search_string)
    context = {"form": form, "companies": companies}
    return render(request, "invoicing/scrape.html", context)


def scraped(request, name):
    all_companies = Customer.objects.all()
    company = get_company(get_company_data(name)[0])
    if company['vat'][0] != 'L':
        company['vat'] = None
    form = CustomerForm(initial={'name': company['name'],
                                 'registration': company['registration'],
                                 'vat': company['vat'],
                                 'address': company['address']})
    context = {
        "company": company,
        "form": form,
        "all_companies": all_companies,
    }

    return render(request, "invoicing/scraped.html", context)

invoicing/templates/invoicing/all_invoices.html
{%  extends "invoicing/layout.html" %}
{% load crispy_forms_tags %}
{% block body %}
<body>
<div class="container">
    <br>
<h4>All Invoices</h4>

{% include "invoicing/invoices.html" %}



{% endblock %}

invoicing/templates/invoicing/customer_profile.html
{%  extends "invoicing/layout.html" %}
{% block body %}

        <div class="container">
            <h4>Customer: {{ customer.name }}</h4>
            <table>
                <tr>
                    <td>ID:</td>
                    <td>{{ customer.id }}</td>
                </tr>
                <tr>
                    <td>Name:</td>
                    <td>{{ customer.name }}</td>
                </tr>
                <tr>
                    <td>Address:</td>
                    <td>{{ customer.address }}</td>
                </tr>
            </table>
            <br>
            <form action="{% url 'new_invoice' customer.id %}">
                <input type="submit" value="New Invoice" />
            </form>
            <br>
            <form action="{% url 'reports:new_report' customer.id %}">
                <input type="submit" value="New Report" />
            </form>
            <br> 
            <hr>
            <h4>Latest Invoices</h4>

            {% include "invoicing/invoices.html" %}
            
            <h4>Latest Reports</h4>
            {% include "reports/all_reports.html" %}
            </div>
            
            <hr>
            
        </div>

    {% endblock %}

invoicing/templates/invoicing/customers.html
{%  extends "invoicing/layout.html" %}
{% block body %}

<div class="container">
    <table class="table">
        {% for customer in customers %}
        <tr>
            <td>{{ customer.id }}</td>
            <td>{{ customer.name  }}</td>
            <td>{{ customer.phone }}</td>
            <td>{{ customer.address }}</td>
            <td><a href="{% url 'customer_profile' customer.id %}">Profile</a></td>
            <td><a href="{% url 'delete_customer' customer.id %}">Delete</a></td>
        </tr>
        {% endfor %}
    </table>
   
</div>
    {% endblock %}

invoicing/templates/invoicing/index.html
{%  extends "invoicing/layout.html" %}
{% load crispy_forms_tags %}
{% block body %}
<body>
<div class="container">
    <br>
<h4>Latest Invoices</h4>

{% include "invoicing/invoices.html" %}

<h4>Latest Reports</h4>
{% include "reports/all_reports.html" %}
</div>

{% endblock %}

invoicing/templates/invoicing/invoices.html
<div class="container">
    <table class="table">
        <tr>
            <th>ID</th>
            <th>Number</th>
            <th>EUR</th>
            <th>Due date</th>
            <th>Paid</th>
            <th>Customer</th>
            <th></th>
            <th></th>
        </tr>
        {% for invoice in invoices %}

        <tr>
            <td>{{ invoice.id }}</td>
            <td>{{ invoice.number  }}</td>
            <td>{{ invoice.total_with_vat|floatformat:2 }}</td>
            <td>{{ invoice.due_date }}</td>
            <td><a href="{% url 'toggle_paid' invoice.id %}">
                {% if invoice.paid %}
                Apmaksāts
                {% else %}
                Nav apmaksāts
                {% endif %}
            </a></td>
            <td>{{ invoice.customer.name }}</td>
            <td><a href="{% url 'process_invoice' invoice.customer.id invoice.id %}">Edit</a></td>
            <td><a href="{% url 'delete_invoice' invoice.id %}">Delete</a></td>
            <td><a href="{% url 'generate_pdf' invoice.id %}">PDF</a></td>
        </tr>
        {% endfor %}
    </table>
   
</div>

invoicing/templates/invoicing/layout.html
{% load static %}



<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Invoicing</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
<link rel="stylesheet" type="text/css" href="{% static 'invoicing/style.css' %}">
</head>
<body>

<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="{% url 'index' %}">Home</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
      <div class="navbar-nav">
        <a class="nav-link active" aria-current="page" href="{% url 'all_invoices' %}">Invoices</a>
        <a class="nav-link" href="{% url 'all_customers' %}">Customers</a>
        <a class="nav-link" href="{% url 'reports:index' %}">Reports</a>
        <a class="nav-link" href="{% url 'new_customer' %}">New Customer</a>
        <a class="nav-link" href="{% url 'scrape' %}">Scrape Customer</a>
        <a class="nav-link" href="{% url 'company:company_info' %}">Company Info</a>
        <a class="nav-link" href="{% url 'users:login_user' %}">Log In</a>
      </div>
    </div>
  </div>
</nav>



{% block body %}
{% if messages %}
  {% for message in messages %}
    {{ message }}
  {% endfor %}
{% endif %}
{% endblock %}
</body>
</html>

invoicing/templates/invoicing/new_customer.html
{%  extends "invoicing/layout.html" %}
{% load crispy_forms_tags %}
{% block body %}


<div class="container">
<form action="{% url 'new_customer' %}" method="post">
    {% csrf_token %}
    {{ form|crispy }}
    <input type="submit" value="Submit">
</form>


</div>
{% endblock %}

invoicing/templates/invoicing/new_invoice.html
{% extends "invoicing/layout.html" %}
{% block body %}


<div class="container">
    <br>
    <h3><a href="{% url 'customer_profile' customer.id %}" class="text-decoration-none">{{ customer.name }}</a></h3>
    <h6>{{ customer.registration }}</h6>
    <h6>{{ customer.vat }}</h6>
    <h6>{{ customer.address }}</h6>
    <hr>
    <p>Invoice Nr. {{ invoice }}</p>
    <br>
    <form action="{% url 'process_invoice' customer.id invoice.id %}" method="post">
        {% csrf_token %}
        <table class="table">
            <tr>
                <th style="width:300px;">Item</th>
                <th style="width: 70px;">Amount</th>
                <th style="width: 70px;">Price</th>
                <th style="width: 70px;">Total</th>
                <th></th>
            </tr>
            {% for line in lines %}
            <tr>

                <td>{{ line.item }}</td>
                <td>{{ line.amount }}</td>
                <td>{{ line.price|floatformat:2 }}</td>
                <td>{{ line.total|floatformat:2 }}</td>
                <td>
                    <button type="button" class="btn btn-danger btn-sm">
                        <a href="{% url 'delete_line' line.id %}" class="text-decoration-none"
                            style="color:inherit">Delete</a>
                    </button>
                </td>
                <td></td>



            </tr>
            {% endfor %}
        </table>

        <table>

            <tr>
                <td>
                    <input name="item" type="text" list="item_list" Placeholder="Enter item.." style="width:300px;">
                    <datalist id="item_list">
                        {% for item in items %}
                        <option value="{{ item }}">
                            {% endfor %}
                    </datalist>

                </td>
                <td>{{ form.amount }}</td>
                <td>{{ form.price }}</td>
                <td>VAT incl: {{ form.vat_included }}</td>
                <td><button type="submit" name="add-line" class="btn btn-primary btn-sm">Add</button></td>

            </tr>

            <tr>
                <td></td>
                <td></td>
                <td>Total: </td>
                <td>{{ invoice.total|floatformat:2 }} EUR</td>
            </tr>
            <tr>
                <td></td>
                <td></td>
                <td>VAT: </td>
                <td>{{ invoice.vat|floatformat:2 }} EUR</td>
            </tr>
            <tr>
                <td></td>
                <td></td>
                <td>Total: </td>
                <td>{{ invoice.total_with_vat|floatformat:2 }} EUR</td>
            </tr>
            <tr>
                <td td colspan="4">{{ invoice.num_to_words }}</td>
                <td></td>
                <td></td>
                <td></td>
            </tr>
            
            <form name="invoice-form" action="{% url 'process_invoice' customer.id invoice.id %}" method="post" novalidate>
                {% csrf_token %}
                <tr>
                    <td colspan="2">Apmaksas termiņš (dienas) {{ due_form.due_time }}</td>
                    <td></td>
                    <td></td>
                    <td><button type="submit" name="save-invoice" class="btn btn-primary">Save Invoice</button></td>
                </tr>
            </form>
        </table>


</div>
{% endblock %}

invoicing/templates/invoicing/scrape.html
{%  extends "invoicing/layout.html" %}
{% load crispy_forms_tags %}
{% block body %}

<div class="container">
    <br>
    <br>
    <br>
    <div class="col-xs-1" align="center">
    <form action="" method="post">
        {% csrf_token %}
        <table>
            <tr>
                <td>Enter company name:</td>
            </tr>
            <tr>
                <td>{{ form.search_string }}</td>
                <td><input type="submit" value="Search"></td>
            </tr>
        </table>
        
       
    </form>

    </div>
    {% for company in companies %}
    <li>
        <a href="{% url 'scraped' company.name %}">
            {{ company.name }}
        </a>
    </li>
    {% endfor %}

   
</div>
    {% endblock %}

invoicing/templates/invoicing/scraped.html
{%  extends "invoicing/layout.html" %}
{% load crispy_forms_tags %}
{% block body %}

<div class="container">

<div class="container">
    <form action="{% url 'new_customer' %}" method="post">
        {% csrf_token %}
        {{ form|crispy }}
        <input type="submit" value="Submit">
    </form>
    <table class="table">
        {% for customer in all_companies %}
        <tr>
            <td>{{ customer.id }}</td>
            <td>{{ customer.name  }}</td>
            <td>{{ customer.phone }}</td>
            <td>{{ customer.address }}</td>
            <td><a href="{% url 'customer_profile' customer.id %}">Profile</a></td>
            <td><a href="{% url 'delete_customer' customer.id %}">Delete</a></td>
        </tr>
        {% endfor %}
    </table>


    

   
</div>
    {% endblock %}